version: "3.3"
services:
        bot:
                build: .
                deploy:
                        restart_policy:
                                condition: any
                                delay: 10s
                                window: 10s
                restart: always